select * from customer limit 20



-- what is the total revenue generated by male vs female customer?

select gender,sum(purchase_amount) as Total_Revenue 
from customer
group by gender




-- which customers used a discount but still spent
-- more than the average amount?

select
customer_id, 
purchase_amount
from customer 
where discount_applied  = 'Yes'
and purchase_amount >= (select avg(purchase_amount)
from customer)





-- which are the top 5 product with the highest average review rating

select
item_purchased,
round(avg(review_rating::numeric),2) as avg_rating
from customer
group by item_purchased
order by avg(review_rating) DESC limit 5



-- Compare the average purchase amount standard and Express Shipping

select
shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in('Express','Standard')
group by shipping_type




-- Do subscribed customer spend more?Compare average spend and total revenue
-- between subscriber and non-subscribers.


select 
subscription_status,
count(customer_id)as Customer_status,
round(avg(purchase_amount),2) as Avg_purchase,
sum(purchase_amount) as Total_revenue
from customer
group by subscription_status
order by total_revenue,avg_purchase desc



-- which 5 product have highest percentage of purchases
-- with discount applied?


select
item_purchased,
round(100*sum(case when
discount_applied = 'Yes' then 1 else 0 end)/count(*),2)as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5





-- Segment customer into New,Returning, and loyal based on their total
-- number of preview purchases,and show the count of each segment.

with Customer_type as (select customer_id,
sum(previous_purchases) as Total_purchses, 
CASE
    when previous_purchases = 1 then 'New_Customer'
	when previous_purchases <= 10 then 'Returning_Customer'
	else 'Loyal_Customer'
end as Customer_Status
from customer 
group by customer_id ,previous_purchases 
order by customer_id
)

select
Customer_Status,
Count(*) as Customer_Count
from Customer_type
group by Customer_Status
order by Customer_Status,Customer_Count





-- what are the top 3 most purchased product within each category.


SELECT 
category,
item_purchased,
total_product_Sale
 from
(select
item_purchased,
sum(previous_purchases) as total_product_Sale,
category,
row_number()OVER(PARTITION by category order by sum(previous_purchases) DESC ) 
as dr
from customer 
GROUP BY item_purchased, category) as ranked
where dr <= 3
order by category,total_product_Sale desc







-- Are Customer who are repeat buyers(more than 5 previous purchase)
-- also likely to subscribe?


select
subscription_Status,
count(customer_id) as repeat_buyers
from Customer
where previous_purchases > 5
group by subscription_Status





-- What is the revenue contribution of each age group?


select 
age_group,
sum(purchase_amount) as Purchase_Contribution
from customer
group by age_group
order by Purchase_Contribution desc



